// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMj64KECTTv_0Ff6RBbzkW_r6yxIOTYEs',
    appId: '1:705270176439:web:6a1c658e9284d1594bcb32',
    messagingSenderId: '705270176439',
    projectId: 'chatoon-858f4',
    authDomain: 'chatoon-858f4.firebaseapp.com',
    storageBucket: 'chatoon-858f4.appspot.com',
    measurementId: 'G-L5XR5V0XWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2QSTjAmSnAbveX5GtwSGV5pKTV8F5q5M',
    appId: '1:705270176439:android:a4a61252559d62094bcb32',
    messagingSenderId: '705270176439',
    projectId: 'chatoon-858f4',
    storageBucket: 'chatoon-858f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQ9-nZ87HwMwtJ4vfytFTh51l6CZxdGc',
    appId: '1:705270176439:ios:b85b54324e8c03a54bcb32',
    messagingSenderId: '705270176439',
    projectId: 'chatoon-858f4',
    storageBucket: 'chatoon-858f4.appspot.com',
    iosClientId: '705270176439-t7i5f329jb2rqtgnev8ipmspufbr4okl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatoonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrQ9-nZ87HwMwtJ4vfytFTh51l6CZxdGc',
    appId: '1:705270176439:ios:b85b54324e8c03a54bcb32',
    messagingSenderId: '705270176439',
    projectId: 'chatoon-858f4',
    storageBucket: 'chatoon-858f4.appspot.com',
    iosClientId: '705270176439-t7i5f329jb2rqtgnev8ipmspufbr4okl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatoonApp',
  );
}
